# Generated by Django 5.1.4 on 2024-12-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0002_category_remove_request_insurance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='filters',
            field=models.ManyToManyField(related_name='foods', to='outfit.category', verbose_name='Категория'),
        ),
        migrations.DeleteModel(
            name='Filter',
        ),
    ]
