# Generated by Django 5.1.4 on 2024-12-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0003_alter_item_filters_delete_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='outfits/', verbose_name='Изображение образа'),
        ),
    ]
